version: '3'
services:
  flask_app:
    build: .
    ports:
    - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl/
    environment:
      SOSISKA_TOKEN: ""
      BOT_NAME: ""
      CHANNEL_NAME: ""
      PUB_CERT: "/etc/nginx/ssl/bot.crt"
      HOST: ""

  bot:
    build: .
    command: ['python', './bot.py']
    environment:
      DEBUG: "no"

  redis:
    image: redis
