version: '3'
services:
  flask_app:
    build: .
    ports:
    - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl/
    environment:
      SOSISKA_TOKEN: "123:XXX"
      BOT_NAME: "@BOT_NAME"
      CHANNEL_NAME: "@CHANNEL_NAME"
      PUB_CERT: "/etc/nginx/ssl/bot.crt"
      HOST: "https://"
    depends_on:
      - "redis"

  bot:
    build: .
    command: ['python', './bot.py']
    environment:
      DEBUG: "no"
      SOSISKA_TOKEN: "123:XXX"

    depends_on:
      - "redis"

  redis:
    image: redis
